# Generated by Django 5.1.4 on 2024-12-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_info', models.CharField(blank=True, max_length=250, verbose_name='Администрирование сайта')),
                ('adress_info', models.CharField(blank=True, max_length=250, verbose_name='Адрес')),
                ('phone_info', models.CharField(blank=True, max_length=250, verbose_name='Телефон')),
                ('email_info', models.CharField(blank=True, max_length=250, verbose_name='E-mail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
