# Generated by Django 5.1.4 on 2024-12-24 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_navigationsettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NavigationSettings',
            new_name='FooterSettings',
        ),
        migrations.AlterModelOptions(
            name='footersettings',
            options={'verbose_name': 'Настройки подвала сайта'},
        ),
    ]
